# services:
#   webserver:
#     build:
#       context: ./backend
#       dockerfile: ./Dockerfile
#     container_name: buldok_webserver
#     ports:
#       - "8080:80"
#     environment:
#       APACHE_DOCUMENT_ROOT: /var/www/html/public
#     volumes:
#       - ./backend:/var/www/html
#     depends_on:
#       - db
#     networks:
#       - buldok-network

#   node:
#     build:
#       context: ./frontend
#     container_name: buldok_node
#     working_dir: /app
#     ports:
#       - "5173:5173"
#     volumes:
#       - ./frontend:/app
#       - /app/node_modules
#     networks:
#       - buldok-network

#   db:
#     image: mariadb:10.4.34
#     container_name: buldok_db
#     restart: always
#     environment:
#       MARIADB_ROOT_PASSWORD: rootpwd
#       MARIADB_DATABASE: buldok
#       MARIADB_USER: user
#       MARIADB_PASSWORD: password
#     ports:
#       - "3306:3306"
#     volumes:
#       - mariadb_data:/var/lib/mysql
#     networks:
#       - buldok-network

#   adminer:
#     image: adminer:5
#     container_name: buldok_adminer
#     restart: always
#     ports:
#       - 5051:8080
#     depends_on:
#       - db
#     networks:
#       - buldok-network

# networks:
#   buldok-network:

# volumes:
#   mariadb_data:

services:
  webserver:
    image: nginx:1.27-alpine
    container_name: buldok_webserver
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/var/www/html
    depends_on:
      - backend
      - frontend
    networks:
      - buldok-network

  # Service 2: PHP-FPM Backend (Symfony)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: buldok_backend
    volumes:
      - ./backend:/var/www/html
    environment:
      DATABASE_URL: "mysql://user:password@db:3306/buldok?serverVersion=mariadb-10.4.34-MariaDB&charset=utf8mb4"
    depends_on:
      - db
    networks:
      - buldok-network

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: buldok_worker
    volumes:
      - ./backend:/var/www/html
    environment:
      DATABASE_URL: "mysql://user:password@db:3306/buldok?serverVersion=mariadb-10.4.34-MariaDB&charset=utf8mb4"
    depends_on:
      - db
    networks:
      - buldok-network
    command: php bin/console-php messenger:consume scheduler_payments -vv

  mercure:
    image: dunglas/mercure:latest
    container_name: buldok_mercure
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      MERCURE_PUBLISHER_JWT_KEY: "!ChangeThisMercureHubJWTSecretKey!"
      MERCURE_SUBSCRIBER_JWT_KEY: "!ChangeThisMercureHubJWTSecretKey!"

      CORS_ALLOWED_ORIGINS: "*"

      SERVER_NAME: ":80"
      MERCURE_ALLOW_ANONYMOUS: "1"
    command: /usr/bin/caddy run --config /etc/caddy/dev.Caddyfile
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "https://localhost/healthz"]
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      - buldok-network

  # redis:
  #   image: redis:latest
  #   container_name: buldok_redis
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - buldok-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: buldok_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "pnpm install && pnpm run dev --host"
    networks:
      - buldok-network

  db:
    image: mariadb:10.4.34
    container_name: buldok_db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootpwd
      MARIADB_DATABASE: buldok
      MARIADB_USER: user
      MARIADB_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - buldok-network

  adminer:
    image: adminer:latest
    container_name: buldok_adminer
    restart: always
    ports:
      - 5051:8080
    depends_on:
      - db
    networks:
      - buldok-network

networks:
  buldok-network:
    driver: bridge

volumes:
  mariadb_data:
