gesdinet_jwt_refresh_token:
  refresh_token_class: App\Entity\RefreshToken
  ttl: 2592000 # 1 mesic
  ttl_update: true

  cookie:
    enabled: true
    same_site: lax
    path: /api/token/refresh
    http_only: true
    secure: false # dev
    remove_token_from_body: true

when@prod:
  gesdinet_jwt_refresh_token:
    cookie:
      secure: true
