lexik_jwt_authentication:
  secret_key: "%env(resolve:JWT_SECRET_KEY)%"
  public_key: "%env(resolve:JWT_PUBLIC_KEY)%"
  pass_phrase: "%env(JWT_PASSPHRASE)%"
  token_ttl: 7200 # 2 hodiny TODO: zmenit na 3600 pred produkci
  set_cookies:
    BEARER:
      httpOnly: true
      lifetime: null
      samesite: lax
      path: /
      secure: false

  token_extractors:
    cookie:
      enabled: true
      name: BEARER

when@prod:
  lexik_jwt_authentication:
    set_cookies:
      BEARER:
        secure: true
