framework:
  messenger:
    # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
    # failure_transport: failed

    transports:
      # https://symfony.com/doc/current/messenger.html#transport-configuration
      async: "%env(MESSENGER_TRANSPORT_DSN)%"
      # failed: 'doctrine://default?queue_name=failed'
      # sync: 'sync://'

    routing:
      App\Message\CheckPaymentsMessage: async # Route your messages to the transports
      # 'App\Message\YourMessage': async

    buses:
      messenger.bus.default:
        middleware:
          # This service will ping the DB before each message.
          # If the connection is gone, it reconnects.
          - doctrine_ping_connection
# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
